/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "sacd_ripper.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ServerRequest, ServerRequest, AUTO)


PB_BIND(ServerResponse, ServerResponse, 4)





